### ISSUE TITLE
Contact Method

### ISSUE THREAD

**Issue by municola** [Rene-Damm/Rene-Damm.github.io#1]
Hi Rene,
I have some questions about the new unity input system on which my startup relies on. Is there any way to contact you? (creating this issue was my only creative idea in order to reach you haha)
Best,
Nicolas

**Comment by Rene-Damm** [comment]
Haha, nice idea :)

You can email me at `<myfirstname>.<mysecondname>ATgmx.net` or DM me on the Unity forum (user name `rdjadu`).
